#include "Constants.h"

const char *PARSER_ERROR[74] =
{
    "",
    "Era esperado fim de programa",
    "Era esperado STRING_",
    "Era esperado CHAR_",
    "Era esperado REAL_NUMBER_",
    "Era esperado INTEGER_NUMBER_",
    "Era esperado BOOLEAN_",
    "Era esperado IDENTIFIER_",
    "Era esperado SET_",
    "Era esperado OF_",
    "Era esperado RECORD_",
    "Era esperado END_",
    "Era esperado LIST_",
    "Era esperado ARRAY_",
    "Era esperado IN_",
    "Era esperado NOT_",
    "Era esperado NIL_",
    "Era esperado CASE_",
    "Era esperado ELSE_",
    "Era esperado THEN_",
    "Era esperado IF_",
    "Era esperado DO_",
    "Era esperado DOWNTO_",
    "Era esperado TO_",
    "Era esperado FOR_",
    "Era esperado WHILE_",
    "Era esperado BEGIN_",
    "Era esperado ASSIGNMENT_",
    "Era esperado VAR_",
    "Era esperado DIV_",
    "Era esperado MOD_",
    "Era esperado AND_",
    "Era esperado OR_",
    "Era esperado WRITE_",
    "Era esperado WRITELN_",
    "Era esperado READ_",
    "Era esperado READLN_",
    "Era esperado FUNCTION_",
    "Era esperado PROCEDURE_",
    "Era esperado TYPE_",
    "Era esperado CONST_",
    "Era esperado PROGRAM_",
    "Era esperado USES_",
    "Era esperado COMMA_",
    "Era esperado DOT_",
    "Era esperado MINUS_",
    "Era esperado PLUS_",
    "Era esperado UPARROW_",
    "Era esperado COLON_",
    "Era esperado SEMI_COLON_",
    "Era esperado DOTDOT_",
    "Era esperado LBRAC_",
    "Era esperado RBRAC_",
    "Era esperado LPAREN_",
    "Era esperado RPAREN_",
    "Era esperado ARROBA_",
    "Era esperado LKEY_",
    "Era esperado RKEY_",
    "Era esperado CONS_",
    "Era esperado OP_MULT_",
    "Era esperado OP_DIV_",
    "Era esperado EQUAL_",
    "Era esperado NOTEQUAL_",
    "Era esperado LT_",
    "Era esperado LE_",
    "Era esperado GT_",
    "Era esperado GE_",
    "Era esperado TYPE_INTEGER_",
    "Era esperado TYPE_REAL_",
    "Era esperado TYPE_CHAR_",
    "Era esperado TYPE_STRING_",
    "Era esperado TYPE_BOOLEAN_",
    "Era esperado TRUE_",
    "Era esperado FALSE_"
};

