#ifndef CONSTANTS_H
#define CONSTANTS_H

enum TokenId 
{
    EPSILON  			= 0,
    DOLLAR   			= 1,
    STRING_				= 2,
    CHAR_				= 3,
    REAL_NUMBER_		= 4,
    INTEGER_NUMBER_		= 5,
    BOOLEAN_			= 6,
    IDENTIFIER_			= 7,
    SET_				= 8,
    OF_					= 9,
    RECORD_				= 10,
    END_				= 11,
    LIST_				= 12,
    ARRAY_				= 13,
    IN_					= 14,
    NOT_				= 15,
    NIL_				= 16,
    CASE_				= 17,
    ELSE_				= 18,
    THEN_				= 19,
    IF_					= 20,
    DO_					= 21,
    DOWNTO_				= 22,
    TO_					= 23,
    FOR_				= 24,
    WHILE_				= 25,
    BEGIN_				= 26,
    ASSIGNMENT_			= 27,
    VAR_				= 28,
    DIV_				= 29,
    MOD_				= 30,
    AND_				= 31,
    OR_					= 32,
    WRITE_				= 33,
    WRITELN_			= 34,
    READ_				= 35,
    READLN_				= 36,
    FUNCTION_			= 37,
    PROCEDURE_			= 38,
    TYPE_				= 39,
    CONST_				= 40,
    PROGRAM_			= 41,
    USES_				= 42,
    COMMA_				= 43,
    DOT_				= 44,
    MINUS_				= 45,
    PLUS_				= 46,
    UPARROW_			= 47,
    COLON_				= 48,
    SEMI_COLON_			= 49,
    DOTDOT_				= 50,
    LBRAC_				= 51,
    RBRAC_				= 52,
    LPAREN_				= 53,
    RPAREN_				= 54,
    ARROBA_				= 55,
    LKEY_				= 56,
    RKEY_				= 57,
    CONS_				= 58,
    OP_MULT_			= 59,
    OP_DIV_				= 60,
    EQUAL_				= 61,
    NOTEQUAL_			= 62,
    LT_					= 63,
    LE_					= 64,
    GT_					= 65,
    GE_					= 66,
    TYPE_INTEGER_		= 67,
    TYPE_REAL_			= 68,
    TYPE_CHAR_			= 69,
    TYPE_STRING_		= 70,
    TYPE_BOOLEAN_		= 71,
    TRUE_				= 72,
    FALSE_				= 73
};

extern const char *PARSER_ERROR[74];

#endif
